---
- name: Deploy da Infraestrutura IoT (Namespace, Mosquitto, InfluxDB)
  hosts: server
  become: yes
  tasks:
    - name: Criar diretório para manifestos
      file:
        path: /tmp/k8s-manifests
        state: directory

    - name: Copiar manifestos para o servidor
      copy:
        src: ../k8s-manifests/
        dest: /tmp/k8s-manifests/

    # CORREÇÃO: Adicionadas aspas ao redor de todo o texto do nome
    - name: "Aplicar configurações (Ordem: Namespace -> Broker -> DB)"
      command: "kubectl apply -f /tmp/k8s-manifests/{{ item }}"
      loop:
        - 00-namespace.yaml
        - 01-mosquitto.yaml
        - 02-influxdb.yaml

    - name: Verificar estado dos Pods
      command: kubectl get pods -n iot-surveillance
      register: pod_status

    - name: Mostrar estado
      debug:
        var: pod_status.stdout_lines