---
- name: Instalar e Configurar o Kubernetes (K3s) no Servidor
  hosts: server
  become: yes 
  tasks:
    - name: Download do script de instalação do K3s
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Executar instalação (Desativar Traefik para usar NodePorts simples)
      command: /tmp/k3s_install.sh
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "--disable traefik"
      
    - name: Garantir que o K3s está ativo
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Aguardar que o Node fique 'Ready'
      command: k3s kubectl get nodes
      register: node_status
      until: "'Ready' in node_status.stdout"
      retries: 10
      delay: 5