apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: iot-surveillance
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    
    listener 8883
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: iot-surveillance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2
        ports:
        - containerPort: 1883
        - containerPort: 8883
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: iot-surveillance
spec:
  type: NodePort
  ports:
    - name: mqtt
      port: 1883
      nodePort: 31883
    - name: mqtts
      port: 8883
      nodePort: 30883 # <--- CORRIGIDO AQUI (antes era 32883)
  selector:
    app: mosquitto