---
# 1. Armazenamento Persistente para o InfluxDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: iot
spec:
  serviceName: influxdb-service
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.7
        ports:
        - containerPort: 8086
          name: api
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: admin
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: password123
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: uminho_mei
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: Iot
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb2
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: influxdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: iot
spec:
  type: NodePort
  ports:
    - name: api
      port: 8086
      targetPort: 8086
      nodePort: 32086
  selector:
    app: influxdb